-- Create audit log table for workflow transitions and task actions

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'audit_log'
  ) THEN
    CREATE TABLE public.audit_log (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      deal_id uuid REFERENCES public.deals(id) ON DELETE CASCADE,
      actor_user_id uuid REFERENCES auth.users(id),
      action text NOT NULL,
      from_status text,
      to_status text,
      metadata jsonb,
      created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
    );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS audit_log_deal_id_idx
  ON public.audit_log(deal_id);
